classname=net.roselyndsshadow.repeataction.RepeatAction
classpath=repeataction.jar
sharedClassLoader=false
# Write in console, autorun.txt, or keybinds.txt:
# bind R "repeataction"
# Comma-separated list of action IDs to ignore (will never be recorded)
ignoreActions=7,1,341,149,326,6,3
