classname=net.roselyndsshadow.repeataction.RepeatAction
classpath=repeataction.jar
sharedClassLoader=false
version=1.5

# Ignore List:
ignoreActions=7,1,341,149,326,6,3,333,332,331,600,183,118

# To use the mod, write in console, autorun.txt, or keybinds.txt:
# bind R "repeataction"
